#|

 Cells Gtk

 Copyright (c) 2004 by Vasilis Margioulas <vasilism@sch.gr>

 You have the right to distribute and use this software as governed by 
 the terms of the Lisp Lesser GNU Public License (LLGPL):

    (http://opensource.franz.com/preamble.html)
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 Lisp Lesser GNU Public License for more details.
 
|#

(in-package :cl-user)

(defpackage :cells-gtk
    (:nicknames :cgtk)
  (:use :common-lisp :pod :cells :gtk-ffi :utils-kt)
  (:export   #:find-widget
             #:with-widget
             #:widget-value
             #:with-widget-value
             #:gtk-user-signals-quit
             #:gtk-continuable-error
             #:gtk-report-error
             #:cgtk-set-active-item-by-path
             #:gtk-combo-box-set-active
             #:show-message
             #:file-chooser
             #:with-markup
             #:push-message
             #:pop-message
             #:pulse
             #:gtk-app
             #:gtk-reset
             #:def-cells-tree-view
             #:def-cells-tree-node
             #:cells-tree-view
             #:cells-tree-node
             #:cells-tree-store
             #:cells-gtk-init

             #:title
             #:icon
             #:tooltips
             #:tooltips-enable
             #:tooltips-delay
             #:allocated-width
             #:allocated-height
             
             #:start-app
             #:start-win
             #:stop-gtk-main
             #:open-windows
             #:init-gtk
             #:close-all-windows
             #:with-gdk-threads
             #:gtk-global-callback-register
             #:gtk-global-callback-funcall
             #:def-populate-adds
             #:populate-adds
             #:with-text-iters
             #:text-buffer-get-text
             #:text-buffer-delete-text
             #:text-buffer-insert-text
             #:text-buffer-append-text
             #:text-buffer-modified-p
             #:text-view-scroll-to-position
             #:gtk-text-buffer-get-iter-at-offset
             #:gtk-text-buffer-get-start-iter
             #:gtk-text-buffer-get-end-iter
             #:gtk-text-buffer-create-mark
             #:gtk-text-view-set-wrap-mode
             #:gtk-text-view-set-editable
             #:gtk-text-buffer-move-mark
             #:gtk-text-view-scroll-mark-onscreen
             #:mk-listbox
             #:mk-treebox
             #:def-columns
             #:callback
             #:callback-if
             #:timeout-add
             #:focus
             #:widget-id
           
             ;; for drawing-area ph

             #:cairo-drawing-area
             #:export-to-file
                                        ; primitives
             #:line
             #:rectangle
             #:arc
             #:path
             #:arrow-line
             #:text-label
                                        ; object handling
             #:move
             #:mk-primitive
             #:modify
             #:remove-primitive
             #:erase
                                        ; create own primitive
             #:def-mk-primitive
             #:defmodify
             #:defdraw
             #:defprimitive
                                        ; accessor funcs for primitives
             #:rgb
             #:alpha
             #:fill-rgb
             #:fill-alpha
             #:fin-1
             #:fin-2
             #:filled
             #:stroked
             #:line-width
             #:p1
             #:p2
             #:p
             #:size
             #:p-min
             #:p-max
             #:c-o-g
             #:radius
             #:angle
             #:widget
             #:anchor-point
             #:docking-point
             #:mouse-over-p             ; does the mouse hover over the primitive?
             #:dragged-p                ; is the primitive being dragged?
             #:draggable
             #:drag-start
             #:selectable
             #:selection
             #:selected-p
                                        ; for the widget
             #:mouse-pos                ; mouse pos over the widget
             #:on-clicked               ; (on-clicked [widget] [button] [primitive])
             #:on-moved                 ; (on-moved [widget] [mouse-pos] [primitive])
             #:on-dragged         ; (on-dragged [widget] [button] [primitive] [start-pos] [end-pos])
             #:hover              ; the primitive the mouse is currently over
             #:dragging           ; the primitive currently being dragged

             #:gl-drawing-area
             #:with-gl-context
             #:init
             #:draw
             ;; symbols from "also exports warning"
             #:rows-count
             #:selected-items-cache
             #:file-chooser-widget
             #:label-align
             #:yscale
             #:mk-toggle-button
             #:mk-drawing-area
             #:use-stock
             #:x-expand
             #:min-width
             #:action-id
             #:clicked
             #:submenu-id
             #:mk-file-chooser
             #:mk-statusbar
             #:menu-item
             #:shadow-id
             #:popup
             #:vscale
             #:show-tabs
             #:resizable
             #:mk-combo-box-entry
             #:hpaned
             #:type-id
             #:on-select-page
             #:entry-completion
             #:tooltip
             #:label
             #:depopulate-popup
             #:column-render
             #:on-value-changed
             #:wintype
             #:sensitive
             #:visible-window
             #:mk-tree-store
             #:box
             #:mk-hbox
             #:mk-item
             #:editable
             #:expand
             #:mk-accel-label
             #:y-pad
             #:deiconify
             #:current-folder
             #:hbox
             #:mk-label
             #:update-policy
             #:is-important
             #:node-render
             #:mk-vscale
             #:items
             #:hseparator
             #:local-only
             #:has-frame
             #:on-toggled
             #:current-name
             #:increments
             #:statusbar
             #:filename
             #:table
             #:image-menu-item
             #:item
             #:expanded
             #:sort-column-id
             #:children-fn
             #:mk-aspect-frame
             #:mk-menu
             #:width
             #:markup
             #:mk-frame
             #:message-dialog
             #:filters-ids
             #:on-show
             #:accel-label-widget
             #:mk-check-button
             #:filters
             #:show-border
             #:radio-button
             #:on-selection-changed
             #:shadow-type
             #:divider-pos
             #:yalign
             #:mk-tree-view
             #:check-button
             #:mk-vpaned
             #:aspect-frame
             #:mk-menu-shell
             #:mk-image
             #:mk-hseparator
             #:resize-mode
             #:text
             #:homogeneous-tabs
             #:relief
             #:frame
             #:kids-list?
             #:auto-update
             #:roots
             #:select-if
             #:elements
             #:columns
             #:homogeneous
             #:tab-pos
             #:buttons-type
             #:event-box
             #:text-buffer
             #:mk-table
             #:show-dialog
             #:mk-expander
             #:mk-check-menu-item
             #:vpaned
             #:use-underline
             #:filter
             #:mk-tooltips
             #:fraction
             #:column-inits
             #:toggle-button
             #:inverted
             #:mk-hpaned
             #:mk-menu-bar
             #:mk-vseparator
             #:accel
             #:mk-range
             #:tab-labels
             #:drawing-area
             #:on-leave
             #:on-changed
             #:mk-tree-view-column
             #:page-size
             #:notebook
             #:show-arrow
             #:border-width
             #:tab-border
             #:fullscreen
             #:fixed-width
             #:cols-count
             #:content-area
             #:iconify
             #:text-view
             #:mk-vbox
             #:uri
             #:separator-menu-item
             #:unfullscreen
             #:line-wrap
             #:calendar
             #:scrollable
             #:tool-item
             #:height
             #:icon-size
             #:entry
             #:of-tree
             #:mk-file-chooser-dialog
             #:spacing
             #:on-day-selected
             #:show-message-dialog
             #:message-type
             #:max-length
             #:value-type
             #:name
             #:mk-toolbar
             #:mk-alignment
             #:scale
             #:mk-spin-button
             #:y-fill
             #:vseparator
             #:mk-file-chooser-widget
             #:placement
             #:select-multiple
             #:max-width
             #:menu-bar
             #:old-popups
             #:mk-list-store
             #:accel-label
             #:mk-arrow
             #:x-fill
             #:current-folder-uri
             #:digits
             #:buttons
             #:on-delete-event
             #:action
             #:cb-quit-id
             #:owner
             #:redraw
             #:mk-entry
             #:xscale
             #:show-page
             #:scrolled-window
             #:xalign
             #:decorated
             #:on-destroy-event
             #:mk-calendar
             #:stock-id
             #:selection-mode
             #:mk-separator-menu-item
             #:expand-all
             #:tool-button
             #:tag-table
             #:has-resize-grip
             #:message
             #:combo-box-entry
             #:make-be
             #:selected-page
             #:tree-view
             #:gtk-value
             #:icon-widget
             #:mk-separator-tool-item
             #:mk-widget
             #:wrap
             #:stock
             #:reorderable
             #:tree-store
             #:y-expand
             #:on-select
             #:hscale
             #:arrow
             #:with-matrix-mode
             #:visible
             #:default-size
             #:mk-text-buffer
             #:mime-types
             #:label-widget
             #:patterns
             #:mk-tool-button
             #:tab-labels-widgets
             #:on-enter
             #:canvas
             #:on-activate
             #:mk-file-filter
             #:above-child
             #:active
             #:mk-window
             #:pulse-step
             #:vbox
             #:mk-event-box
             #:fn-response
             #:progress-bar
             #:on-draw
             #:list-store
             #:columns-def
             #:sort-indicator
             #:obey-child
             #:unmaximize
             #:range
             #:mk-notebook
             #:clickable
             #:draw-value
             #:mk-radio-button
             #:combo-box
             #:mk-combo-box
             #:buttons-id
             #:file-filter
             #:buffer
             #:use-preview-label
             #:mk-box
             #:window
             #:column-types
             #:icon-size-id
             #:file-chooser-dialog
             #:mk-button
             #:on-focus
             #:accel-group
             #:padding
             #:item-types
             #:policy
             #:on-expose-event
             #:menu
             #:image
             #:mk-message-dialog
             #:completion
             #:spin-button
             #:mode
             #:mk-tool-item
             #:orientation
             #:page-increment
             #:contexts
             #:mk-image-menu-item
             #:current-page
             #:mk-progress-bar
             #:on-modified-changed
             #:on-pressed
             #:tearoff-menu-item
             #:check-menu-item
             #:style
             #:to-be
             #:value-pos
             #:menu-shell
             #:populate-popup
             #:x-pad
             #:on-hide
             #:on-released
             #:right-justified
             #:mk-entry-completion
             #:text-column
             #:mk-container
             #:mk-menu-item
             #:mk-scale
             #:tree-model
             #:mk-tearoff-menu-item
             #:toolbar
             #:tree-view-column
             #:radio-menu-item
             #:button
             #:mk-text-view
             #:separator-tool-item
             #:mk-radio-menu-item
             #:on-edit
             #:print-fn
             #:mk-scrolled-window
             #:current-pos
             #:maximize
             #:use-markup
             #:mk-hscale
             #:expander
             #:alignment
             ;; from other packages
             #:fill
             #:shadow
             #:min
             #:max
             #:model
             #:position
             #:step
             #:container
             #:ratio
             #:type
             ))
