
(in-package :gtk-ffi)

(def-gtk-lib-functions :gdk 
  (gdk-gc-new ((drawable c-pointer))
      c-pointer)
  (gdk-draw-line ((drawable c-pointer)
		  (gc c-pointer)
		  (x1 int)
		  (y1 int)
		  (x2 int)
		  (y2 int)))
  (gdk-pixmap-new ((drawable c-pointer)
		   (width int)
		   (height int)
		   (depth int))
     c-pointer)
  (gdk-draw-drawable ((drawable c-pointer)
		      (gc c-pointer)
		      (src c-pointer)
		      (xsrc int)
		      (ysrc int)
		      (xdest int)
		      (ydest int)
		      (width int)
		      (height int)))
  (gdk-draw-rectangle ((drawable c-pointer)
		       (gc c-pointer)
		       (filled boolean)
		       (x int)
		       (y int)
		       (width int)
		       (height int)))
  (gdk-gc-set-rgb-fg-color ((gc c-pointer)
			    (color c-pointer)))
  (gdk-gc-set-rgb-bg-color ((gc c-pointer)
			    (color c-pointer)))
  (gdk-color-parse ((spec c-string)
		    (color c-pointer))
      int)
  (gdk-draw-layout ((drawable c-pointer)
		    (gc c-pointer)
		    (x int)
		    (y int)
		    (pango-layout c-pointer)))
  (gdk-gc-set-line-attributes ((gc c-pointer)
			       (line-width int)
			       (line-style int)
			       (cap-style int)
			       (join-style int))))
		   



